"""Per-lesson content enrichments for the 5->10 variation expansion.

For each lesson, adds:
  - 4 new TRUE facts (different angles than existing 8 -- what it is / why it matters
                      / when it helps / common mistake)
  - 4 new silly WRONGS (varying absurdity registers -- surreal-physical, false-confident,
                        anthropomorphic, time-loop)
  - 2 new SCENARIO question dicts (situational, kid-grade)

Quality bar: 2nd-grade reading level, no jargon without inline plain English,
no lying-as-strategy, no shame, no hide-forever, no food-as-code, no fantasy
wizards, no metaphor traps. Wrongs must be obviously absurd -- never plausible-but-false.

Imported by expand_lessons_v3.py and merged into SEEDS at runtime.
"""
from __future__ import annotations

from typing import Any


def _scn(prompt: str, opts: list[tuple[str, bool]]) -> dict:
    return {"prompt": prompt, "options": [{"text": t, "correct": c} for t, c in opts]}


# Each entry: lesson_id -> { "facts": [4 strs], "wrongs": [4 strs], "scenarios": [2 _scn dicts] }
ENRICHMENTS: dict[int, dict[str, Any]] = {
    1: {
        "facts": [
            "A computer follows tiny steps super, super fast.",
            "Most computers can't do anything until you give them power.",
            "When you click a button, the computer does many tiny jobs at once.",
            "A computer never gets bored even if you ask it the same thing all day.",
        ],
        "wrongs": [
            "A computer can sniff your snacks from another room.",
            "Computers prefer when you whisper instead of type.",
            "A computer needs a tiny pillow before it will work.",
            "A computer grows new keys overnight if you forget to feed it.",
        ],
        "scenarios": [
            _scn("Bytey's tablet won't turn on. What's the FIRST thing to check?",
                [("Is it plugged in or charged?", True),
                 ("Is the room loud enough for the tablet?", False),
                 ("Has it had its breakfast yet?", False),
                 ("Is the moon full?", False)]),
            _scn("A friend says: 'My fridge has a screen so it's a computer.' Is that totally right?",
                [("Sort of -- many fridges DO have a small computer inside!", True),
                 ("No way -- fridges are made of soup.", False),
                 ("Only if the fridge is wearing socks.", False),
                 ("Only on holidays.", False)]),
        ],
    },
    2: {
        "facts": [
            "If you don't say what you want, Claude can't guess it.",
            "Claude is the same Claude every day -- no moods, no bad days.",
            "Claude can help you start a project, even when you feel stuck.",
            "Claude only knows what you typed -- it can't see your screen.",
        ],
        "wrongs": [
            "Claude has a tiny dog that barks at bad questions.",
            "Claude is allergic to the letter Q.",
            "Claude can read what you're THINKING if you concentrate.",
            "Claude charges 3 cookies per question.",
        ],
        "scenarios": [
            _scn("You type just 'help me' to Claude. What should you ADD?",
                [("Say what you want help with.", True),
                 ("Beg three times in a row.", False),
                 ("Add a sad face.", False),
                 ("Promise to feed it later.", False)]),
            _scn("Claude gave you an answer you don't like. What's a smart next step?",
                [("Ask it to try again, but tell it what to change.", True),
                 ("Tell it that it is bad.", False),
                 ("Hide your computer in the closet.", False),
                 ("Wait three days and ask the same question.", False)]),
        ],
    },
    3: {
        "facts": [
            "A variable is a labeled box where you keep a number or word.",
            "You can change what's IN the box later -- that's the whole point.",
            "Naming the box clearly helps you remember what's inside.",
            "Two boxes can hold the same value but still have different names.",
        ],
        "wrongs": [
            "Variables float in the air until they get tired.",
            "A variable changes color when you look away.",
            "Variables only work on Wednesdays after lunch.",
            "Each variable has tiny legs and walks home at night.",
        ],
        "scenarios": [
            _scn("Bytey writes: score = 10. Then later: score = 20. What's in the box now?",
                [("20 -- the new value replaced the old one.", True),
                 ("Both 10 and 20 stacked on top of each other.", False),
                 ("Just '30' because they got added.", False),
                 ("Nothing -- variables empty themselves.", False)]),
            _scn("Which variable name tells you the most about what's inside?",
                [("playerScore", True),
                 ("x", False),
                 ("thingie", False),
                 ("a", False)]),
        ],
    },
    4: {
        "facts": [
            "A sticky-note rule means: write down what to remember.",
            "Computers forget everything when they turn off -- unless you save.",
            "Saving keeps your work safe even if the power goes out.",
            "A good name on your save makes it easy to find later.",
        ],
        "wrongs": [
            "Sticky notes glow if you tell them a secret.",
            "If you save a game, the computer prints out a real sticky note.",
            "Memory only works if your computer has had a nap.",
            "The computer remembers things by humming a tune.",
        ],
        "scenarios": [
            _scn("You worked on a drawing for an hour and didn't save. The power goes out. What happens?",
                [("Your drawing is probably gone -- save next time!", True),
                 ("It saves itself with a backup brain.", False),
                 ("The computer remembers from the smell.", False),
                 ("It comes back if you say please.", False)]),
            _scn("Which file name will help future-you find your save?",
                [("dragon-game-level1.json", True),
                 ("a.json", False),
                 ("file.json", False),
                 ("untitled-untitled.json", False)]),
        ],
    },
    5: {
        "facts": [
            "Computers do math by following the same rules every time.",
            "If you give a computer 1 + 1, it always gives back 2.",
            "Computers can do millions of math problems while you blink.",
            "Math is the language computers think in.",
        ],
        "wrongs": [
            "Computers do math by counting their feet.",
            "Computers prefer odd numbers because they look funny.",
            "When numbers get too big, computers eat them.",
            "Math is hard for computers when it's raining.",
        ],
        "scenarios": [
            _scn("Bytey asks the computer: 5 + 3. What does it say?",
                [("8, instantly.", True),
                 ("Maybe 8, maybe 7 -- depends on its mood.", False),
                 ("It refuses unless paid in stickers.", False),
                 ("It tells a joke instead.", False)]),
            _scn("Why is math good for computers but tricky for people sometimes?",
                [("Computers don't get tired or bored -- they just keep going.", True),
                 ("Computers have more fingers than people.", False),
                 ("Computers wear special math hats.", False),
                 ("People don't like even numbers.", False)]),
        ],
    },
    6: {
        "facts": [
            "Alan Turing dreamed of a machine that could think like a person.",
            "His idea became the blueprint for every modern computer.",
            "He showed that machines could solve any problem they were given steps for.",
            "The 'Turing test' asks: can you tell a person from a computer just by chatting?",
        ],
        "wrongs": [
            "Turing built the first computer out of pancakes.",
            "Turing's machine could only think on Sundays.",
            "Turing taught his computer to bark like a dog.",
            "Turing's first computer was the size of a peanut.",
        ],
        "scenarios": [
            _scn("Why did Turing's idea matter so much for the world?",
                [("It showed every computer could do anything if given the right steps.", True),
                 ("It made computers cheaper to grow on trees.", False),
                 ("It helped computers learn to whistle.", False),
                 ("It made math illegal in some places.", False)]),
            _scn("In a Turing test, what are you trying to figure out?",
                [("Whether you're chatting with a person or a computer.", True),
                 ("What the computer ate for breakfast.", False),
                 ("How many fingers the computer has.", False),
                 ("Whether the computer is sleepy.", False)]),
        ],
    },
    7: {
        "facts": [
            "A perceptron is the tiniest part of an AI brain.",
            "It looks at inputs and decides 'yes' or 'no'.",
            "Many perceptrons together can recognize a cat in a photo.",
            "The first perceptron was built in 1958 -- older than your parents!",
        ],
        "wrongs": [
            "A perceptron eats one cracker per question.",
            "Perceptrons get hiccups if you ask them too many things.",
            "A perceptron is a kind of small flower.",
            "Perceptrons close their eyes during hard problems.",
        ],
        "scenarios": [
            _scn("Why does AI need MANY perceptrons working together?",
                [("One alone can only make tiny decisions -- many can recognize complex things.", True),
                 ("Perceptrons get lonely on their own.", False),
                 ("They like to play tag during questions.", False),
                 ("They share crackers between themselves.", False)]),
            _scn("What does a perceptron do with the inputs you give it?",
                [("Adds them up and checks if they cross a line -- yes or no.", True),
                 ("Stares at them until one wins a contest.", False),
                 ("Sings them to sleep.", False),
                 ("Throws them into a tiny basket.", False)]),
        ],
    },
    8: {
        "facts": [
            "AI learns by trying, getting it wrong, and trying again.",
            "Each mistake helps the AI get a tiny bit better.",
            "Without practice, an AI can't learn anything new.",
            "Back-and-forth learning is just like how YOU learn to ride a bike.",
        ],
        "wrongs": [
            "AI learns by listening to soft jazz.",
            "AI gets smarter by drinking ten glasses of water.",
            "AI only learns when nobody is watching.",
            "AI learns by reading dictionaries in its sleep.",
        ],
        "scenarios": [
            _scn("Why is making mistakes important for AI learning?",
                [("Each mistake shows the AI what to fix next time.", True),
                 ("Mistakes make the AI feel guilty so it works harder.", False),
                 ("Mistakes earn the AI a small trophy.", False),
                 ("Mistakes teach the AI to dance.", False)]),
            _scn("How is AI learning similar to how YOU learn to ride a bike?",
                [("You wobble, fall, get up, and try again -- same idea.", True),
                 ("You both wear helmets at all times.", False),
                 ("You both grow taller from practice.", False),
                 ("You both prefer to learn at midnight.", False)]),
        ],
    },
    9: {
        "facts": [
            "Attention means the AI focuses on the most important words.",
            "Without attention, an AI gets confused on long sentences.",
            "Attention helps the AI know that 'the cat' goes with 'sleeps' in a sentence.",
            "Attention is one of the big inventions that made modern AI smart.",
        ],
        "wrongs": [
            "Attention only works if you say 'pretty please' first.",
            "AI attention runs out after 10 questions and needs a nap.",
            "Attention costs the AI a tiny coin every time.",
            "AI attention bounces off shiny objects.",
        ],
        "scenarios": [
            _scn("In the sentence 'The dog chased the ball', what does AI 'attention' help with?",
                [("Knowing that 'dog' is the one doing the chasing.", True),
                 ("Counting how many letters there are.", False),
                 ("Spelling the words backwards.", False),
                 ("Picking the prettiest word.", False)]),
            _scn("Why do longer sentences need MORE attention?",
                [("More words means more connections to keep track of.", True),
                 ("Long sentences make the AI sleepy.", False),
                 ("Long sentences are heavier to lift.", False),
                 ("Long sentences cost extra.", False)]),
        ],
    },
    10: {
        "facts": [
            "An LLM is born by reading huge piles of text -- books, websites, everything.",
            "It learns patterns of which word usually follows another.",
            "Training takes weeks of hard work for the computers.",
            "After training, the LLM is the same brain everyone uses.",
        ],
        "wrongs": [
            "An LLM is born when two computers do a special handshake.",
            "An LLM hatches from a giant glowing egg.",
            "LLMs grow on tall metal trees.",
            "LLMs only train at night because of magic.",
        ],
        "scenarios": [
            _scn("What does an LLM mostly DO during training?",
                [("Reads tons of words and learns which words go together.", True),
                 ("Sleeps and dreams about answers.", False),
                 ("Has small computer parties.", False),
                 ("Counts to a billion.", False)]),
            _scn("After training is done, can the LLM still learn from your one chat?",
                [("Not from one chat -- its training is locked in.", True),
                 ("Yes, it remembers every question forever.", False),
                 ("Only if you talk loudly.", False),
                 ("Only if you say its name backwards.", False)]),
        ],
    },
}

# Lessons 11-20: AI helpers + prompting basics
ENRICHMENTS.update({
    11: {
        "facts": [
            "Claude is great at thinking through tricky problems step by step.",
            "Claude likes when you say what KIND of help you want.",
            "Claude can write stories, plans, and explanations.",
            "Claude is the same Claude on any computer -- same brain.",
        ],
        "wrongs": [
            "Claude lives in a tiny house inside your keyboard.",
            "Claude has 7 cousins named Carl, Carla, and 5 more Claudes.",
            "Claude answers faster if you spin in a circle.",
            "Claude only helps if you wear matching socks.",
        ],
        "scenarios": [
            _scn("You ask Claude: 'Help me with my project.' Claude wants more info. Why?",
                [("'Project' could mean anything -- Claude needs to know what kind.", True),
                 ("Claude is teasing you.", False),
                 ("Claude needs your home address first.", False),
                 ("Claude is allergic to projects.", False)]),
            _scn("What is Claude really good at?",
                [("Thinking carefully and explaining the steps.", True),
                 ("Predicting the weather next year.", False),
                 ("Smelling cookies through the screen.", False),
                 ("Telling time without a clock.", False)]),
        ],
    },
    12: {
        "facts": [
            "Cursor edits code right inside your editor.",
            "Cursor can rename a thing across many files in one go.",
            "Cursor is super fast -- it shows changes instantly.",
            "Cursor reads your code to understand what you mean.",
        ],
        "wrongs": [
            "Cursor types code with tiny invisible fingers.",
            "Cursor needs a sip of water every 50 lines.",
            "Cursor only works on Tuesdays before 3 PM.",
            "Cursor sings every change like a song.",
        ],
        "scenarios": [
            _scn("You want to rename 'spd' to 'speed' in 4 files. What does Cursor do?",
                [("It changes them all at once, super fast.", True),
                 ("It changes one file and sends you the others by mail.", False),
                 ("It tells you to do it yourself.", False),
                 ("It adds the word 'banana' instead.", False)]),
            _scn("Cursor is BEST when you want to:",
                [("Make small or big changes to code that already works.", True),
                 ("Order a pizza online.", False),
                 ("Turn on the lights in your room.", False),
                 ("Sing happy birthday.", False)]),
        ],
    },
    13: {
        "facts": [
            "Gemini can look at words AND pictures at the same time.",
            "Gemini is good for searching and finding facts.",
            "Gemini helps when you have a photo and want to know what's in it.",
            "Gemini is made by Google, which also makes the search engine.",
        ],
        "wrongs": [
            "Gemini sees the world through two pairs of glasses.",
            "Gemini can taste pictures.",
            "Gemini grew up in a treehouse.",
            "Gemini answers questions in haiku form.",
        ],
        "scenarios": [
            _scn("You take a photo of a flower and want to know its name. Which helper?",
                [("Gemini -- it can see the photo and tell you.", True),
                 ("A regular calculator.", False),
                 ("A mirror.", False),
                 ("A toaster oven.", False)]),
            _scn("What makes Gemini different from helpers that only read text?",
                [("Gemini can also LOOK at pictures and understand them.", True),
                 ("Gemini speaks in cat language.", False),
                 ("Gemini is shorter than other helpers.", False),
                 ("Gemini only works at night.", False)]),
        ],
    },
    14: {
        "facts": [
            "Codex turns plain English into real code.",
            "Codex helps you write code without remembering every keyword.",
            "Codex shows finished code, ready to run.",
            "Codex is great when you know what you want but not how to type it.",
        ],
        "wrongs": [
            "Codex writes code by stamping tiny letters.",
            "Codex needs a magic password before it will work.",
            "Codex types upside down for fun.",
            "Codex saves all the code in a giant cookie jar.",
        ],
        "scenarios": [
            _scn("You say 'Codex, write a loop that counts to 5'. What does Codex do?",
                [("Writes real code that does exactly that.", True),
                 ("Asks if 5 is a lucky number.", False),
                 ("Writes a song called 'Five'.", False),
                 ("Makes you count first.", False)]),
            _scn("Codex is BEST when you want to:",
                [("Get code written for an idea you can describe in words.", True),
                 ("Set the dinner table.", False),
                 ("Tie your shoes faster.", False),
                 ("Pick a movie to watch.", False)]),
        ],
    },
    15: {
        "facts": [
            "Open source means anyone can read and use the code for free.",
            "Open helpers can be fixed and improved by anyone in the world.",
            "Open code lives on websites where everyone can see it.",
            "Many open helpers cost zero dollars to use.",
        ],
        "wrongs": [
            "Open code only works if everyone clicks 'I trust you'.",
            "Open code is invisible until midnight.",
            "Open helpers wear bright open-toed shoes.",
            "Open code can only be opened with a special key.",
        ],
        "scenarios": [
            _scn("You find a bug in an open helper. What CAN you do?",
                [("Read the code yourself and try to fix it!", True),
                 ("Send the helper to a doctor.", False),
                 ("Whisper the bug to a tree.", False),
                 ("Wait for the bug to fix itself.", False)]),
            _scn("Why is 'open' good for the whole coding world?",
                [("Anyone can study it, improve it, and share their improvements.", True),
                 ("It opens new doors automatically.", False),
                 ("It saves whales.", False),
                 ("It has a built-in alarm clock.", False)]),
        ],
    },
    16: {
        "facts": [
            "Ollama runs an AI right on your own computer.",
            "Ollama works even with no internet -- no WiFi needed.",
            "What you ask Ollama stays on your computer, totally private.",
            "Ollama is slower than cloud helpers but doesn't need a server.",
        ],
        "wrongs": [
            "Ollama is a real llama you keep in your closet.",
            "Ollama only works if your computer is happy.",
            "Ollama recharges by spinning in circles.",
            "Ollama types using its tail.",
        ],
        "scenarios": [
            _scn("Your WiFi is out. Can you still use Ollama?",
                [("Yes! Ollama runs on your computer, no internet needed.", True),
                 ("No, Ollama needs the moon to be full.", False),
                 ("Only if you say its name three times.", False),
                 ("Only after midnight.", False)]),
            _scn("Why might someone WANT to use a slower helper like Ollama?",
                [("Privacy -- their words stay on their own computer.", True),
                 ("Slow helpers taste better.", False),
                 ("Slow helpers are friendlier.", False),
                 ("Slow helpers know more cat facts.", False)]),
        ],
    },
    17: {
        "facts": [
            "Different helpers are good at different things.",
            "Pick the helper that matches what you're trying to do.",
            "If one helper isn't getting it, try a different one!",
            "Some helpers are fast, some are thoughtful -- both are useful.",
        ],
        "wrongs": [
            "Always use the helper with the prettiest icon.",
            "Pick the helper that's closest to your house.",
            "Never use the same helper twice in one day.",
            "The helper with the longest name is always smartest.",
        ],
        "scenarios": [
            _scn("You want code written quickly from a description. Which helper?",
                [("Codex -- it turns words into code fast.", True),
                 ("A microwave.", False),
                 ("A stopwatch.", False),
                 ("A magic 8-ball.", False)]),
            _scn("You want to find facts about the moon. Which helper?",
                [("Gemini -- it's great at searching.", True),
                 ("A spoon.", False),
                 ("A compass.", False),
                 ("A jump rope.", False)]),
        ],
    },
    18: {
        "facts": [
            "Smart coders ASK before they BUILD.",
            "Asking the AI for ideas first saves you from wasted work.",
            "When you ask first, you can pick the best plan before typing code.",
            "Asking is a sign of being smart, not lazy!",
        ],
        "wrongs": [
            "Build first, ask after -- it's faster anyway.",
            "Asking is only for beginners.",
            "Real coders never ask for help.",
            "If you ask, the AI gives you a sticker every time.",
        ],
        "scenarios": [
            _scn("You want to make a guessing game. What's the SMART first step?",
                [("Ask the AI to help plan the rules and steps.", True),
                 ("Type code with your eyes closed.", False),
                 ("Bury yourself in pillows.", False),
                 ("Wait until tomorrow.", False)]),
            _scn("Why does asking BEFORE building save time?",
                [("You catch problems in the plan, not after writing the wrong code.", True),
                 ("Asking gives the AI a hug.", False),
                 ("Asking earns you a free pizza.", False),
                 ("Asking makes the screen bigger.", False)]),
        ],
    },
    19: {
        "facts": [
            "Specific words help the AI know exactly what you want.",
            "Vague words like 'thing' or 'stuff' make the AI guess.",
            "Saying 'a red ball' is clearer than saying 'an object'.",
            "The more specific you are, the closer the AI gets to your idea.",
        ],
        "wrongs": [
            "Saying 'thingy' is the most powerful word in coding.",
            "The AI prefers vague questions because they're more relaxing.",
            "Specific words make the AI cry tears of joy.",
            "If you're TOO specific, the AI gets jealous.",
        ],
        "scenarios": [
            _scn("Which prompt will get a better answer from the AI?",
                [("Make a button that says 'Play' in big blue letters.", True),
                 ("Make a thing that does the thing.", False),
                 ("Just figure it out!", False),
                 ("You know what I want.", False)]),
            _scn("You want the AI to draw a hero. What helps MOST?",
                [("Describe what the hero looks like -- color, size, shape.", True),
                 ("Just say 'hero' and hope.", False),
                 ("Draw a frowny face on your keyboard.", False),
                 ("Whisper at the screen.", False)]),
        ],
    },
    20: {
        "facts": [
            "Showing examples helps the AI understand exactly what you want.",
            "An example is worth a thousand vague descriptions.",
            "If the AI keeps getting it wrong, give it a tiny example.",
            "Examples teach the AI the SHAPE of your idea.",
        ],
        "wrongs": [
            "Examples confuse the AI because there are too many.",
            "Showing an example uses up your daily AI battery.",
            "Examples only work in Spanish.",
            "The AI ignores examples on rainy days.",
        ],
        "scenarios": [
            _scn("You want the AI to write a poem about your cat. What helps?",
                [("Show one short poem you already like as a model.", True),
                 ("Hide what you want until the AI guesses.", False),
                 ("Send the AI a real cat.", False),
                 ("Type only emojis.", False)]),
            _scn("Bytey says: 'show, don't tell.' What does that mean for prompting?",
                [("Give the AI an example of what you want, not just words about it.", True),
                 ("Tell the AI to be quiet.", False),
                 ("Use only your hands, no typing.", False),
                 ("Show the AI your shoe.", False)]),
        ],
    },
})

# Lessons 21-30: prompting + safety + memory
ENRICHMENTS.update({
    21: {
        "facts": [
            "Doing things one at a time helps the AI focus.",
            "If you ask 5 things at once, the AI might miss some.",
            "Step-by-step works better than all-at-once.",
            "One task per message is the cleanest way to ask.",
        ],
        "wrongs": [
            "The AI loves a long list of 100 tasks at once.",
            "Asking many things at once unlocks a secret level.",
            "The AI works faster if you write one giant sentence.",
            "Mixing tasks is the secret of pro coders.",
        ],
        "scenarios": [
            _scn("You want to: pick a hero, name them, and choose their power. What's the smart way?",
                [("Ask one thing first, then move to the next.", True),
                 ("Ask all three in one breath.", False),
                 ("Skip naming and rush.", False),
                 ("Do them all at midnight.", False)]),
            _scn("Why do step-by-step asks work better?",
                [("The AI gives a focused answer for each step.", True),
                 ("Steps make the AI taller.", False),
                 ("Steps cost less battery.", False),
                 ("Steps are required by law.", False)]),
        ],
    },
    22: {
        "facts": [
            "If the answer isn't right, asking again with more detail often fixes it.",
            "It's totally OK to say 'try again, but make it shorter'.",
            "Each ask-again teaches the AI more about what you really want.",
            "Don't be afraid to ask 5, 10, even 20 times -- coders do this!",
        ],
        "wrongs": [
            "Asking again hurts the AI's feelings.",
            "You only get one ask per question, then it's over.",
            "Asking twice in a row breaks the computer.",
            "If you ask too many times, the AI logs out forever.",
        ],
        "scenarios": [
            _scn("The AI's first answer is too long. What do you do?",
                [("Ask again: 'shorter, please -- just 3 sentences'.", True),
                 ("Give up on the topic forever.", False),
                 ("Print it out and hide it.", False),
                 ("Tell the AI it failed forever.", False)]),
            _scn("Bytey gets a wrong answer 4 times in a row. What's the smart thing?",
                [("Try a totally different way to ask the question.", True),
                 ("Yell at the screen.", False),
                 ("Throw the keyboard.", False),
                 ("Wait for the AI to guess your mood.", False)]),
        ],
    },
    23: {
        "facts": [
            "Some things should never go into a chat with AI: passwords, addresses, secrets.",
            "If a website asks for your real name, ask a parent first.",
            "AI helpers don't know what's safe -- that's YOUR job.",
            "When in doubt, leave it out.",
        ],
        "wrongs": [
            "Always type your full address so the AI knows where to send help.",
            "Telling the AI your password makes it work faster.",
            "The AI keeps your secrets in a tiny safe just for you.",
            "It's polite to share your home phone number with every AI.",
        ],
        "scenarios": [
            _scn("The AI asks: 'What's your home address?' What should you do?",
                [("Don't share it -- and tell a parent the AI asked.", True),
                 ("Share it so the AI feels closer to you.", False),
                 ("Give a fake one and hope.", False),
                 ("Type it three times to be sure.", False)]),
            _scn("Why are passwords NEVER for sharing with chat AI?",
                [("Anyone could be reading the chat -- your password could be stolen.", True),
                 ("The AI gets jealous of long passwords.", False),
                 ("Passwords make the AI sneeze.", False),
                 ("Passwords break the keyboard.", False)]),
        ],
    },
    24: {
        "facts": [
            "Memory in computers means storing things to use later.",
            "Without memory, every program would forget itself in a second.",
            "Saving your game uses memory on a long-term spot.",
            "Some memory is fast and small, some is slow and huge.",
        ],
        "wrongs": [
            "Robot memory works only on Tuesdays.",
            "Memory is made of tiny dreams.",
            "Computers store memory in their tiny hats.",
            "Memory only counts if it's in pencil.",
        ],
        "scenarios": [
            _scn("You save your game. Where does that save go?",
                [("Into a memory spot on your computer or in the cloud.", True),
                 ("Into a tiny notebook the computer keeps under its desk.", False),
                 ("Onto a balloon that floats away.", False),
                 ("It vanishes -- saves are pretend.", False)]),
            _scn("Why is memory important for a game?",
                [("So your high score and progress don't disappear when you close it.", True),
                 ("So the game can practice while you sleep.", False),
                 ("So the game stays warm.", False),
                 ("So the game knows your shoe size.", False)]),
        ],
    },
    25: {
        "facts": [
            "My memory rules: don't store secrets in the chat.",
            "Real names, schools, and home info stay OFFLINE.",
            "If you wouldn't tell a stranger, don't type it to AI.",
            "Adults can help you decide what's safe to share.",
        ],
        "wrongs": [
            "Always tell the AI your school name to get smarter answers.",
            "Sharing your real birthday gives you bonus points.",
            "Type your phone number to unlock the deluxe AI.",
            "The AI loves it when you share your bedroom number.",
        ],
        "scenarios": [
            _scn("A site asks for your school name. What's the safe move?",
                [("Skip it -- or ask an adult first.", True),
                 ("Type the school name AND principal's name.", False),
                 ("Make up a long fake school name.", False),
                 ("Type your school AND your friend's school.", False)]),
            _scn("Why are 'memory rules' for sharing personal info important?",
                [("To keep YOU safe online.", True),
                 ("To make the AI happy.", False),
                 ("To unlock more colors.", False),
                 ("To get a free hat.", False)]),
        ],
    },
    26: {
        "facts": [
            "Slash commands are quick shortcuts -- like /help.",
            "Type / and the helper shows a list of magic spells.",
            "Slash commands save typing for things you do often.",
            "Each helper has its own set of slash commands.",
        ],
        "wrongs": [
            "Slash commands only work if you say 'abracadabra' first.",
            "Each slash command costs a real coin.",
            "Slash commands are typed with your nose.",
            "Slash means 'stop' in helper language.",
        ],
        "scenarios": [
            _scn("You want a list of all the magic spells. What do you type?",
                [("Just type / to see all the commands.", True),
                 ("Type 'magic, please'.", False),
                 ("Knock on the screen.", False),
                 ("Wait for spells to fall from the sky.", False)]),
            _scn("Why are slash commands useful?",
                [("They save you from typing the same long phrase over and over.", True),
                 ("They make the AI dance.", False),
                 ("They unlock secret food levels.", False),
                 ("They turn off gravity.", False)]),
        ],
    },
    27: {
        "facts": [
            "A skill is a custom command you teach the AI.",
            "When you make a skill, you save the steps to do something later.",
            "Skills are like tiny recipes the AI can follow.",
            "Once you build a skill, the AI can use it any time.",
        ],
        "wrongs": [
            "Skills only stay alive for 24 hours.",
            "A skill must be approved by a real wizard.",
            "You can only make 3 skills before the AI gets dizzy.",
            "Skills disappear when the moon is full.",
        ],
        "scenarios": [
            _scn("You make the same chart every Friday. What's smart to do?",
                [("Build a skill so the AI can do it for you next time.", True),
                 ("Hide and hope someone else makes it.", False),
                 ("Make charts on Saturdays only.", False),
                 ("Quit charts forever.", False)]),
            _scn("A skill is most like:",
                [("A recipe the AI can follow whenever you say.", True),
                 ("A song the AI hums.", False),
                 ("A dance the AI does.", False),
                 ("A tiny coat the AI wears.", False)]),
        ],
    },
    28: {
        "facts": [
            "Always check what the AI gave you before using it.",
            "Even smart helpers make small mistakes sometimes.",
            "Reading the answer carefully is part of being a good coder.",
            "Trust but verify: trust the AI to try, verify the result yourself.",
        ],
        "wrongs": [
            "If the AI says it, it's always right -- don't double-check.",
            "Checking the AI's work makes the AI sad.",
            "Verifying takes 100 hours so just skip it.",
            "AI never makes mistakes -- only humans do.",
        ],
        "scenarios": [
            _scn("The AI gives you code that LOOKS right. What's the smart move?",
                [("Run it and see if it actually works.", True),
                 ("Trust it forever, never test.", False),
                 ("Sing it to your goldfish.", False),
                 ("Email it to grandma.", False)]),
            _scn("Why is 'check your work' important for AI answers?",
                [("AI can be wrong, and you might not notice if you don't look.", True),
                 ("To make the AI feel watched.", False),
                 ("It's the law in 6 countries.", False),
                 ("It earns you free juice.", False)]),
        ],
    },
    29: {
        "facts": [
            "An error message is the computer telling you what went wrong.",
            "Reading the error word-by-word usually points right at the problem.",
            "Errors aren't bad -- they're clues to fix the bug.",
            "The line number in an error tells you where to look.",
        ],
        "wrongs": [
            "Errors are punishment for asking too many questions.",
            "Ignore errors -- they go away after 5 minutes.",
            "Errors are written in invisible ink most of the time.",
            "Each error means you owe the computer a cookie.",
        ],
        "scenarios": [
            _scn("Your code says: 'SyntaxError: missing parenthesis on line 5'. What do you do?",
                [("Look at line 5 and add the missing parenthesis.", True),
                 ("Cry softly into the keyboard.", False),
                 ("Delete line 5 forever.", False),
                 ("Ignore it and run again.", False)]),
            _scn("Errors are most like:",
                [("A treasure map showing exactly where the bug is hiding.", True),
                 ("A scolding from your computer.", False),
                 ("A list of bad words.", False),
                 ("A song the computer sings.", False)]),
        ],
    },
    30: {
        "facts": [
            "Tell what happened: 'I typed X, and Y happened instead of Z'.",
            "Clear bug reports help others fix the bug fast.",
            "Always say what you EXPECTED vs what you GOT.",
            "A good bug report is short, honest, and specific.",
        ],
        "wrongs": [
            "Bug reports must be at least 1,000 words long.",
            "Always include 5 emoji per sentence.",
            "Real coders never explain bugs -- just complain.",
            "Bug reports work better in rhyme.",
        ],
        "scenarios": [
            _scn("Your game won't start. What's the BEST thing to write to a helper?",
                [("'I clicked Play. Nothing happened. The screen stayed black.'", True),
                 ("'It is broken!! HELP'", False),
                 ("'Hi how are you'", False),
                 ("'Game bad'", False)]),
            _scn("What 3 things should every bug report have?",
                [("What you did, what you expected, what actually happened.", True),
                 ("Your favorite color, song, and snack.", False),
                 ("The weather, your shoe size, and one secret.", False),
                 ("A drawing, a poem, and a song.", False)]),
        ],
    },
})

# Lessons 31-40: trying again + game basics
ENRICHMENTS.update({
    31: {
        "facts": [
            "If one way doesn't work, try a different angle.",
            "Stuck on a problem? Take a break and come back fresh.",
            "Most bugs are fixed by the 3rd or 4th approach, not the 1st.",
            "Asking 'what else could I try?' unlocks new ideas.",
        ],
        "wrongs": [
            "There is only one right way to fix every bug.",
            "Trying again means you failed.",
            "After 2 tries, you must give up forever.",
            "Real coders fix everything on the first try.",
        ],
        "scenarios": [
            _scn("You tried 3 ways to make the hero jump and none work. What now?",
                [("Step away, then come back and try a totally different approach.", True),
                 ("Quit coding forever.", False),
                 ("Hide the keyboard.", False),
                 ("Pretend you wanted no jump.", False)]),
            _scn("Why is 'trying a different way' important?",
                [("Each approach teaches you something new about the problem.", True),
                 ("Each try gives you a sticker.", False),
                 ("After 5 tries, the computer awards you a hat.", False),
                 ("Trying differently bends time.", False)]),
        ],
    },
    32: {
        "facts": [
            "A game world is everything the player can see and touch.",
            "Worlds are made of layers: sky, ground, characters, items.",
            "Each layer can be turned on or off to change the look.",
            "A simple world starts with just one layer -- like a flat ground.",
        ],
        "wrongs": [
            "A game world is built from real grass and tape.",
            "Worlds appear only when no one is looking.",
            "Game worlds run on tiny windmills.",
            "Worlds collapse if anyone forgets to clap.",
        ],
        "scenarios": [
            _scn("Your world has a sky, a ground, and a hero. What if you turn off the ground?",
                [("The hero would fall through nothing -- broken world!", True),
                 ("The sky takes over and becomes the new ground.", False),
                 ("Nothing happens because the world is invincible.", False),
                 ("The hero starts to fly.", False)]),
            _scn("Why are worlds made of LAYERS?",
                [("So you can build, change, and fix one piece at a time.", True),
                 ("To stack them like sandwiches.", False),
                 ("Layers smell better than one big piece.", False),
                 ("Layers earn you bonus tickets.", False)]),
        ],
    },
    33: {
        "facts": [
            "Input is what the player does -- like pressing a key.",
            "Action is what the game does in response -- like moving the hero.",
            "Result is what the player sees afterward -- like the hero in a new spot.",
            "Every game has this loop running constantly.",
        ],
        "wrongs": [
            "Input only works on weekdays.",
            "Action skips itself sometimes for fun.",
            "Result is invisible until the next day.",
            "The loop runs backwards on holidays.",
        ],
        "scenarios": [
            _scn("Player taps RIGHT arrow. Hero slides right. Player sees it move. What's the ACTION?",
                [("Hero slides right.", True),
                 ("Player taps right.", False),
                 ("Player sees it move.", False),
                 ("The screen takes a nap.", False)]),
            _scn("Why is the input -> action -> result loop SO important?",
                [("Without it, the game doesn't respond to the player at all.", True),
                 ("Without it, the screen turns purple.", False),
                 ("It's a tradition.", False),
                 ("It's required for cake.", False)]),
        ],
    },
    34: {
        "facts": [
            "A sprite is a picture in your game -- usually the hero or an enemy.",
            "A costume is a different look for the same sprite.",
            "Swapping costumes is how you animate walking, jumping, etc.",
            "Sprites can change costume many times per second.",
        ],
        "wrongs": [
            "Sprites are real fairies trapped in your screen.",
            "Costumes only work on Halloween.",
            "Each sprite has 1,000 costumes by default.",
            "Costumes change themselves randomly.",
        ],
        "scenarios": [
            _scn("Your hero needs to look like they're walking. What do you do?",
                [("Swap between 2 or 3 costumes that show different leg positions.", True),
                 ("Add a tiny treadmill to the screen.", False),
                 ("Yell 'walk!' at the sprite.", False),
                 ("Wait for the sprite to learn on its own.", False)]),
            _scn("Why are costumes useful for animation?",
                [("Quick costume changes look like motion to the eye.", True),
                 ("They make the sprite warmer.", False),
                 ("They earn the sprite extra coins.", False),
                 ("They scare away bugs.", False)]),
        ],
    },
    35: {
        "facts": [
            "Move your hero by changing its X (left-right) and Y (up-down).",
            "When the player presses LEFT, you subtract from X.",
            "When the player presses UP, you usually subtract from Y (up is less Y).",
            "Smooth movement happens when you change position many times per second.",
        ],
        "wrongs": [
            "X and Y are the names of the hero's pet parrots.",
            "To move, you yell 'go' at the hero.",
            "Heroes only move when no one is looking.",
            "Movement is decided by the weather.",
        ],
        "scenarios": [
            _scn("Player presses RIGHT arrow. What math should happen to the hero?",
                [("Hero's X gets a tiny bit bigger (moves right).", True),
                 ("Hero teleports to the moon.", False),
                 ("Hero gets a snack.", False),
                 ("X turns into Y suddenly.", False)]),
            _scn("Why does the game change position MANY times per second?",
                [("Many tiny moves blur together as smooth motion.", True),
                 ("To keep the screen warm.", False),
                 ("To use up the battery.", False),
                 ("Because the law says so.", False)]),
        ],
    },
    36: {
        "facts": [
            "A hitbox is an invisible box around your sprite.",
            "When two hitboxes touch, the game knows they collided.",
            "Hitboxes are usually a bit smaller than the sprite for fairness.",
            "Without hitboxes, your hero would walk through walls.",
        ],
        "wrongs": [
            "Hitboxes glow purple when activated.",
            "Hitboxes are made of jelly.",
            "Each hitbox has a tiny bell that rings.",
            "Hitboxes only work for the first 5 seconds.",
        ],
        "scenarios": [
            _scn("Your hero walks through walls. What's probably wrong?",
                [("The wall is missing a hitbox.", True),
                 ("The wall is too tired today.", False),
                 ("The hero is wearing a cape.", False),
                 ("Your computer is upside down.", False)]),
            _scn("Why are hitboxes USUALLY smaller than the sprite?",
                [("So the game feels fair -- small overlaps don't count as a hit.", True),
                 ("So they fit in tiny boxes.", False),
                 ("So they save space.", False),
                 ("So they don't make noise.", False)]),
        ],
    },
    37: {
        "facts": [
            "Gravity in a game pulls objects down a tiny bit each frame.",
            "Without gravity, your hero would float forever.",
            "Stronger gravity makes the hero fall faster.",
            "Real gravity comes from Earth -- game gravity is fake but it FEELS real.",
        ],
        "wrongs": [
            "Game gravity comes from a tiny magnet behind the screen.",
            "Heroes fall up unless told otherwise.",
            "Gravity only works when the hero is hungry.",
            "Game gravity charges the computer's battery.",
        ],
        "scenarios": [
            _scn("Your hero floats and won't come down. What's missing?",
                [("Gravity -- code that adds to Y each frame.", True),
                 ("A heavy backpack.", False),
                 ("Sad music.", False),
                 ("A sticker.", False)]),
            _scn("If you DOUBLE the gravity, what happens to the hero?",
                [("Falls twice as fast.", True),
                 ("Turns blue and floats up.", False),
                 ("Becomes 2 heroes.", False),
                 ("Wins the game instantly.", False)]),
        ],
    },
    38: {
        "facts": [
            "Score goes up when you do something good -- like grabbing a coin.",
            "Lives count how many tries you have left.",
            "Lose all your lives and the game ends.",
            "Score and lives let the game tell you how you're doing.",
        ],
        "wrongs": [
            "Score is measured in tomatoes.",
            "Lives must be returned to the library.",
            "If your score gets too high, the game gets jealous.",
            "Lives are made of clouds.",
        ],
        "scenarios": [
            _scn("Hero grabs a coin. What should happen?",
                [("Score goes up by some amount (like +10).", True),
                 ("Hero turns into a coin.", False),
                 ("The coin turns into a hero.", False),
                 ("Nothing -- coins are decoration.", False)]),
            _scn("You have 3 lives and just got hit. What changes?",
                [("Lives drop to 2.", True),
                 ("Lives go up because you're brave.", False),
                 ("Lives become invisible.", False),
                 ("Lives multiply by 0.", False)]),
        ],
    },
    39: {
        "facts": [
            "A level is one part of the game with its own challenges.",
            "Beat one level to unlock the next.",
            "Levels usually get harder as you go.",
            "A game with many levels gives the player something to work toward.",
        ],
        "wrongs": [
            "All levels must be the exact same color.",
            "Levels skip themselves randomly.",
            "Each level has a tiny door at the bottom.",
            "Levels argue with each other about who's hardest.",
        ],
        "scenarios": [
            _scn("Why do most games have multiple levels?",
                [("So players have new challenges and stay interested.", True),
                 ("To use up disk space.", False),
                 ("Because levels reproduce.", False),
                 ("To make the game heavier.", False)]),
            _scn("How does Level 5 USUALLY compare to Level 1?",
                [("Harder -- more enemies, faster, or trickier.", True),
                 ("Exactly the same.", False),
                 ("Easier than Level 1.", False),
                 ("Made of cheese.", False)]),
        ],
    },
    40: {
        "facts": [
            "Win condition: a goal that ends the game with a celebration.",
            "Lose condition: something that ends the game without success.",
            "Both conditions must be CLEAR so the player knows what to aim for.",
            "Without a win or lose, players don't feel any accomplishment.",
        ],
        "wrongs": [
            "Win and lose are the same thing in disguise.",
            "Most games skip win conditions -- too much work.",
            "Lose conditions only fire on Tuesdays.",
            "Winning is illegal in some kinds of games.",
        ],
        "scenarios": [
            _scn("Your game has no win condition. What's the problem?",
                [("Players never feel like they accomplished anything.", True),
                 ("The game weighs more.", False),
                 ("Players win automatically every time.", False),
                 ("The game becomes invisible.", False)]),
            _scn("A clear lose condition might be:",
                [("Hero falls off the bottom of the screen.", True),
                 ("Hero takes a nap.", False),
                 ("It starts raining inside the game.", False),
                 ("The hero's hat goes missing.", False)]),
        ],
    },
})

# Lessons 41-50: polish + iteration
ENRICHMENTS.update({
    41: {
        "facts": [
            "Polish means small touches that make a game FEEL great.",
            "Sound effects, screen shake, and tiny animations are polish.",
            "Without polish, even good ideas feel boring.",
            "A game with 5% polish feels 50% better.",
        ],
        "wrongs": [
            "Polish only works if applied with a special cloth.",
            "Polish is just for shoes, not games.",
            "Polish costs $5 per click.",
            "Polish makes games heavier and slower.",
        ],
        "scenarios": [
            _scn("Two games are identical except one has a 'pop' sound when you grab a coin. Which feels better?",
                [("The one with the sound -- that's polish at work.", True),
                 ("The silent one feels mysterious.", False),
                 ("Doesn't matter, sound is just noise.", False),
                 ("Sound makes games glitch.", False)]),
            _scn("What's a SIMPLE polish you can add to any game?",
                [("A tiny shake when the hero gets hit.", True),
                 ("A 50-page menu screen.", False),
                 ("A real cake delivered after the game.", False),
                 ("A loud alarm that never stops.", False)]),
        ],
    },
    42: {
        "facts": [
            "Going from idea to plan turns dreams into doable steps.",
            "Write your idea down first -- even one sentence helps.",
            "Break a big idea into smaller ones until each fits in one sentence.",
            "A plan with 5 small steps beats an idea with no steps.",
        ],
        "wrongs": [
            "Plans are for chickens -- real coders just type.",
            "Writing the plan uses up the idea.",
            "Plans must be at least 10 pages.",
            "Plans only work if signed by a wizard.",
        ],
        "scenarios": [
            _scn("Your idea: 'Make a pet game.' First step to turn it into a plan?",
                [("Write down what kind of pet, then what it can do.", True),
                 ("Just start typing code with closed eyes.", False),
                 ("Tell only one person, then forget it.", False),
                 ("Wait 1 year for inspiration.", False)]),
            _scn("Why break a big idea into smaller pieces?",
                [("Each small piece is something you can finish today.", True),
                 ("Big pieces hurt to carry.", False),
                 ("Small pieces sparkle.", False),
                 ("Small pieces are illegal in some games.", False)]),
        ],
    },
    43: {
        "facts": [
            "A color editor lets you pick the look of every part of your game.",
            "Colors set the mood -- bright = happy, dark = scary.",
            "Two colors next to each other can clash or harmonize.",
            "Pick a small set of colors and stick to them for a clean look.",
        ],
        "wrongs": [
            "Use 50+ colors for the strongest game.",
            "Color choice doesn't matter to humans.",
            "Some colors hate other colors -- it's a fact.",
            "Colors only work on Mondays.",
        ],
        "scenarios": [
            _scn("You want your game to feel SCARY. What colors might help?",
                [("Dark blue, deep purple, dim red.", True),
                 ("Bright pink, sunny yellow, lime green.", False),
                 ("White and rainbow at the same time.", False),
                 ("Tan and beige forever.", False)]),
            _scn("Your game uses 30 different colors and looks like a mess. What's the fix?",
                [("Cut down to 4-5 colors that all work together.", True),
                 ("Add 30 more colors.", False),
                 ("Make every color invisible.", False),
                 ("Yell at the screen.", False)]),
        ],
    },
    44: {
        "facts": [
            "A level editor lets you build levels by clicking instead of coding.",
            "You drag blocks, paint backgrounds, and place enemies.",
            "Level editors save your work as a file you can load later.",
            "Many famous games (like Mario Maker) ARE level editors!",
        ],
        "wrongs": [
            "Level editors require a paint brush you actually own.",
            "Each block costs a real dollar.",
            "Level editors only edit one level then break.",
            "Level editors only work for square levels.",
        ],
        "scenarios": [
            _scn("Why is a level editor easier than coding levels?",
                [("You can SEE what you're making as you click and drag.", True),
                 ("Editors do the design for you.", False),
                 ("Editors are louder.", False),
                 ("Editors give you free coins.", False)]),
            _scn("You designed a cool level. What do you do next?",
                [("Save it so you can play it again.", True),
                 ("Forget it on purpose.", False),
                 ("Print it out.", False),
                 ("Bury the file.", False)]),
        ],
    },
    45: {
        "facts": [
            "You can ask AI to add a feature to your game by describing it.",
            "Be specific: 'Add a jump that makes the hero go up when I press space'.",
            "The AI shows you the code to add -- your job is to plug it in.",
            "Asking AI for features is a real coder skill.",
        ],
        "wrongs": [
            "Yell at the AI until it adds the feature.",
            "AI features only stay for 30 seconds.",
            "AI charges $1 per feature.",
            "Real features must be drawn first.",
        ],
        "scenarios": [
            _scn("You want to add coins to your game. What's the smart prompt?",
                [("'Add code that drops 5 coins on the level. Hero collects them by touching.'", True),
                 ("'Make it cooler!'", False),
                 ("'You know what I mean.'", False),
                 ("'Coins.'", False)]),
            _scn("AI gives you code for the feature. Next step?",
                [("Add the code to your game and test it.", True),
                 ("Frame the code on the wall.", False),
                 ("Email the code to grandma.", False),
                 ("Print and forget.", False)]),
        ],
    },
    46: {
        "facts": [
            "A platformer is a game where the hero jumps on platforms.",
            "Mario, Sonic, and many others are platformers.",
            "Your first platformer can be tiny -- just a hero, a floor, and a goal.",
            "Each iteration (try) makes the platformer better.",
        ],
        "wrongs": [
            "Platformers must have at least 100 platforms.",
            "Real platformers can only be played with one hand.",
            "Platforms float because of secret invisible balloons.",
            "Platformers were invented yesterday.",
        ],
        "scenarios": [
            _scn("What's the SIMPLEST first platformer?",
                [("Hero stands on a floor, jumps, and reaches a flag.", True),
                 ("100 levels with bosses on every screen.", False),
                 ("A racing game with cars.", False),
                 ("A puzzle game with words.", False)]),
            _scn("Why start small with your first platformer?",
                [("You can finish it and learn what works before adding more.", True),
                 ("Small games are heavier.", False),
                 ("Big games are illegal at home.", False),
                 ("Tiny games run on candles.", False)]),
        ],
    },
    47: {
        "facts": [
            "Showing a friend means watching them play -- and watching their face!",
            "Friends find bugs you'd never spot yourself.",
            "Take notes when they get stuck or laugh -- both are gold.",
            "Listen, don't argue. Their experience is the truth.",
        ],
        "wrongs": [
            "Tell your friend they played wrong.",
            "If they don't like it, the friendship is over.",
            "Real testing is done alone in a closet.",
            "Friend testing is for amateurs.",
        ],
        "scenarios": [
            _scn("Your friend gets stuck on level 1 and looks frustrated. What do you do?",
                [("Make a note -- level 1 is too hard. Don't argue.", True),
                 ("Tell your friend they're playing wrong.", False),
                 ("Send your friend to bed.", False),
                 ("Erase the level so they can't play.", False)]),
            _scn("Why is showing a friend better than testing alone?",
                [("Friends find problems you've gotten used to and can't see anymore.", True),
                 ("Friends bring snacks every time.", False),
                 ("Friends fix bugs by accident.", False),
                 ("Friends know all the rules.", False)]),
        ],
    },
    48: {
        "facts": [
            "Saving means storing your game so it doesn't disappear.",
            "Sharing means giving your game to other people to try.",
            "A good save uses a clear file name with what's inside.",
            "Sharing is how YOUR game becomes part of someone else's day.",
        ],
        "wrongs": [
            "Saves only work if you blow on the disk.",
            "Sharing your game gives it away forever.",
            "Saved games shrink every Tuesday.",
            "You can only share with one person ever.",
        ],
        "scenarios": [
            _scn("You want a friend across town to try your game. What do you need to do?",
                [("Save it, then share the file with your friend.", True),
                 ("Walk over and play it on YOUR computer.", False),
                 ("Tell your friend to imagine the game.", False),
                 ("Mail your computer to the friend.", False)]),
            _scn("What's a GOOD save file name?",
                [("dragon-game-v3.json", True),
                 ("a.json", False),
                 ("file.json", False),
                 ("untitled-thingie-final-final-USE-THIS.json", False)]),
        ],
    },
    49: {
        "facts": [
            "A wish is the BIG dream behind your game.",
            "Knowing your wish helps you decide what to add or skip.",
            "Examples: 'I want a kid to laugh' or 'I want a player to feel brave'.",
            "Every part of your game should serve the wish.",
        ],
        "wrongs": [
            "A wish must be spoken to a real shooting star.",
            "Wishes count only on holidays.",
            "Real coders don't wish -- they just type.",
            "Wishes use up your daily creativity.",
        ],
        "scenarios": [
            _scn("Your wish: 'I want kids to feel brave.' Now you're picking enemies. Which fits?",
                [("Slow, scary monsters the kid CAN beat with practice.", True),
                 ("Impossible bosses no one can ever defeat.", False),
                 ("No enemies at all.", False),
                 ("100 enemies that all win.", False)]),
            _scn("Why is having a 'wish' useful when designing a game?",
                [("It tells you which features fit and which to leave out.", True),
                 ("It earns you a free hat.", False),
                 ("Wishes are required by game law.", False),
                 ("Wishes scare bugs away.", False)]),
        ],
    },
    50: {
        "facts": [
            "Iteration 1: get the hero standing on the floor.",
            "Start with the simplest possible thing that works.",
            "Even a hero on a floor with no game IS progress.",
            "Each iteration adds one tiny feature on top.",
        ],
        "wrongs": [
            "Iteration 1 must include 50 features.",
            "If iteration 1 is simple, you've failed.",
            "Iteration 1 only counts if it has music.",
            "Real coders skip iteration 1.",
        ],
        "scenarios": [
            _scn("Iteration 1 is just a hero on a floor. Should you stop and celebrate?",
                [("Yes! That's a real working part of a game.", True),
                 ("No -- only completed games count.", False),
                 ("Only if the hero is wearing red.", False),
                 ("Only on Sundays.", False)]),
            _scn("Why start so SIMPLE in iteration 1?",
                [("You catch problems early and build confidence.", True),
                 ("Simple things are illegal in big games.", False),
                 ("Simple uses up your creativity coupon.", False),
                 ("Simple is for tiny screens only.", False)]),
        ],
    },
})

# Lessons 51-60: capstone iterations + game design
ENRICHMENTS.update({
    51: {
        "facts": [
            "Iteration 2 adds JUMPING -- the hero can leave the floor.",
            "Jumping needs gravity to bring the hero back down.",
            "Test the jump 10 times to find the right height.",
            "Too low feels boring, too high feels floaty.",
        ],
        "wrongs": [
            "Jumping only works if the hero is wearing sneakers.",
            "Jumps cost the hero one tooth each.",
            "If the hero jumps too much, the screen breaks.",
            "Jumping requires sunlight.",
        ],
        "scenarios": [
            _scn("You added jumping but the hero floats up forever. What's missing?",
                [("Gravity to pull the hero back down.", True),
                 ("Special jumping shoes.", False),
                 ("A countdown timer.", False),
                 ("More music.", False)]),
            _scn("Your jump is too high -- feels weird. What do you do?",
                [("Lower the jump value and test again.", True),
                 ("Quit and start a new game.", False),
                 ("Add 100 more enemies.", False),
                 ("Tell the hero to jump quieter.", False)]),
        ],
    },
    52: {
        "facts": [
            "Iteration 3 adds COINS and SCORE -- reasons to keep playing.",
            "Hero touches a coin -> score goes up -> coin disappears.",
            "Score gives the player a goal even without enemies.",
            "Pick how many points each coin is worth.",
        ],
        "wrongs": [
            "Coins must be made of real metal.",
            "Score only counts on the player's birthday.",
            "Each coin must be unique and have a name.",
            "Score is invisible until the game ends.",
        ],
        "scenarios": [
            _scn("Hero touches coin. Score is 0. Each coin = 10. What's the new score?",
                [("10.", True),
                 ("0 -- coins reset score.", False),
                 ("100.", False),
                 ("Negative 10.", False)]),
            _scn("Why add coins BEFORE adding enemies?",
                [("Coins give a positive goal -- fun to chase before fear arrives.", True),
                 ("Coins are required by law.", False),
                 ("Coins make the screen brighter.", False),
                 ("Coins prevent enemies from existing.", False)]),
        ],
    },
    53: {
        "facts": [
            "Iteration 4 adds a BAD GUY -- something to avoid.",
            "Bad guys move on a pattern (back and forth, in a circle, etc.).",
            "Touch the bad guy -> lose a life or game over.",
            "Bad guys make the game feel exciting and risky.",
        ],
        "wrongs": [
            "Bad guys are required to wear masks.",
            "Each bad guy must have a real name.",
            "Bad guys are paid in cookies.",
            "Bad guys never move on weekends.",
        ],
        "scenarios": [
            _scn("Your first bad guy walks back and forth on a platform. Why is that good?",
                [("It's predictable -- the player can learn the timing.", True),
                 ("It's required by the bad-guy union.", False),
                 ("Bad guys can only walk in straight lines.", False),
                 ("Walking saves battery.", False)]),
            _scn("Why does a bad guy make a game more fun?",
                [("Risk + skill = excitement when you avoid them.", True),
                 ("Bad guys make the screen warmer.", False),
                 ("Bad guys count toward your score.", False),
                 ("Bad guys buy more lives.", False)]),
        ],
    },
    54: {
        "facts": [
            "Iteration 5 adds a POWER-UP -- something that helps the hero.",
            "Power-ups give the hero a special ability for a short time.",
            "Common power-ups: speed, double-jump, shield.",
            "Power-ups make players feel awesome briefly.",
        ],
        "wrongs": [
            "Power-ups must be eaten with a fork.",
            "Power-ups last forever and never expire.",
            "Each power-up must come with a song.",
            "Power-ups only work on rainbow Mondays.",
        ],
        "scenarios": [
            _scn("Hero touches a star -- what should happen?",
                [("Hero gets a special power for a few seconds, then back to normal.", True),
                 ("The star calls the hero on the phone.", False),
                 ("The hero turns into a star forever.", False),
                 ("Nothing -- stars are decoration.", False)]),
            _scn("Why are power-ups USUALLY temporary?",
                [("If they lasted forever, the game would be too easy.", True),
                 ("Permanent power-ups are illegal.", False),
                 ("Power-ups get tired.", False),
                 ("The hero's pocket only fits short ones.", False)]),
        ],
    },
    55: {
        "facts": [
            "Iteration 6 adds a FLAG and a REVEAL -- the win moment.",
            "The flag is the goal at the end of the level.",
            "Reaching the flag triggers a fun reveal -- confetti, music, a message.",
            "The reveal makes the win feel REAL and earned.",
        ],
        "wrongs": [
            "Flags must be made of real cloth.",
            "Reveals only happen if the hero blinks first.",
            "Flags walk away if the hero is too slow.",
            "Reveals are tiny and easy to miss on purpose.",
        ],
        "scenarios": [
            _scn("Hero touches the flag. What should happen?",
                [("A celebration -- confetti, win message, music!", True),
                 ("Nothing -- that would be greedy.", False),
                 ("The screen turns black silently.", False),
                 ("The flag asks for a tip.", False)]),
            _scn("Why is the REVEAL so important?",
                [("Players need to FEEL their accomplishment, not just be told.", True),
                 ("Reveals are required by federal law.", False),
                 ("Reveals attract bonus pixels.", False),
                 ("Reveals run on plant power.", False)]),
        ],
    },
    56: {
        "facts": [
            "A good idea is fun, doable, and clear in one sentence.",
            "If you can't explain your idea quickly, it might be too big.",
            "Pick ideas YOU would want to play -- that's the magic.",
            "Good ideas often start small and grow.",
        ],
        "wrongs": [
            "Good ideas must be approved by a committee.",
            "Bigger ideas are always better than small ones.",
            "Good ideas come only at midnight.",
            "Ideas must be exactly 47 words long.",
        ],
        "scenarios": [
            _scn("Which is a GOOD first-game idea?",
                [("'A cat dodges water drops.' (small + clear)", True),
                 ("'A 100-hour epic with 50 characters and online multiplayer.'", False),
                 ("'Something cool maybe.'", False),
                 ("'A game.'", False)]),
            _scn("Why does 'fits in one sentence' matter?",
                [("If you can say it simply, you can probably build it.", True),
                 ("One-sentence games are tax-deductible.", False),
                 ("Short ideas are louder.", False),
                 ("Sentences are limited.", False)]),
        ],
    },
    57: {
        "facts": [
            "Listening for problems means really HEARING what people say.",
            "If 3 people complain about the same thing, it's probably real.",
            "Don't argue with feedback -- collect it, then decide.",
            "Problems are gifts: they show you what to fix.",
        ],
        "wrongs": [
            "Problems are punishment for being a bad coder.",
            "If someone complains, ignore them and they'll forget.",
            "Real games never have problems.",
            "Listen only to people who agree with you.",
        ],
        "scenarios": [
            _scn("3 friends say your jump is too floaty. What's the smart move?",
                [("Believe them -- fix the jump.", True),
                 ("Tell them they're wrong.", False),
                 ("Make the jump even floatier to teach them.", False),
                 ("Block them from playing.", False)]),
            _scn("Why is feedback a GIFT, not a complaint?",
                [("It shows you exactly what to improve next.", True),
                 ("It's wrapped in shiny paper.", False),
                 ("Feedback comes with snacks.", False),
                 ("Feedback can be returned for store credit.", False)]),
        ],
    },
    58: {
        "facts": [
            "An idea spark is the moment you go 'oh, what if I tried THIS?'",
            "Sparks come from playing other games, reading, walking, or talking.",
            "Write sparks down -- they fade fast.",
            "Most great games started as a tiny spark.",
        ],
        "wrongs": [
            "Sparks only happen during lightning storms.",
            "Real coders have sparks scheduled at 3 PM daily.",
            "Sparks must be approved by a librarian.",
            "Sparks fly away if you don't catch them in a jar.",
        ],
        "scenarios": [
            _scn("You think 'what if my hero could SHRINK?' This is a spark. What do you do?",
                [("Write it down before you forget!", True),
                 ("Wait for the spark to write itself.", False),
                 ("Tell the spark to come back tomorrow.", False),
                 ("Erase the idea on purpose.", False)]),
            _scn("Where do GOOD idea sparks usually come from?",
                [("Playing games, reading, walking -- anywhere your brain wanders.", True),
                 ("Only from a special spark room.", False),
                 ("Only from the helper who gives them out.", False),
                 ("Only on the day before a holiday.", False)]),
        ],
    },
    59: {
        "facts": [
            "A hook is the thing that makes someone want to play.",
            "Good hooks are short -- like 'a robot who can't stop dancing'.",
            "If you can describe your hook in one sentence, it's strong.",
            "The hook is the one thing your game does better than any other.",
        ],
        "wrongs": [
            "A hook must be made of real metal.",
            "Real games don't need hooks -- that's old-fashioned.",
            "Hooks are paid by the word.",
            "Hooks are illegal in 4 states.",
        ],
        "scenarios": [
            _scn("Pick the BEST hook for a kid game:",
                [("'A puppy who collects rainbows by sneezing.'", True),
                 ("'A complicated game with stuff.'", False),
                 ("'It's a game.'", False),
                 ("'You should play this.'", False)]),
            _scn("Why does a SHORT hook work better than a long one?",
                [("It's easy to remember and easy to share.", True),
                 ("Short hooks weigh less.", False),
                 ("Short hooks are required.", False),
                 ("Short hooks taste better.", False)]),
        ],
    },
    60: {
        "facts": [
            "Make your game means actually doing it -- not just dreaming.",
            "Even a tiny game IS a game. You did the thing.",
            "Share what you made with someone who matters to you.",
            "The first game is the hardest. The next ones get easier.",
        ],
        "wrongs": [
            "Real games take 10 years and a team of 100.",
            "If you finish, you must immediately make a sequel.",
            "Games made by kids don't count.",
            "Only games on TV are real games.",
        ],
        "scenarios": [
            _scn("You finish your tiny first game. What do you do?",
                [("Show someone -- and feel proud!", True),
                 ("Hide it forever in shame.", False),
                 ("Delete it for being small.", False),
                 ("Pretend you never made it.", False)]),
            _scn("Why is FINISHING more important than making something perfect?",
                [("A finished tiny game teaches you more than 10 unfinished masterpieces.", True),
                 ("Perfect things break the universe.", False),
                 ("Finishing is required by your shoe.", False),
                 ("Finished games are made of cake.", False)]),
        ],
    },
})
